// Code generated by MockGen. DO NOT EDIT.
// Source: issues.go
//
// Generated by this command:
//
//	mockgen -source=issues.go -destination=mock/issues_mock.go -package=mock
//
// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	usecase "github.com/igsr5/github-project-automation/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockIssueFetcher is a mock of IssueFetcher interface.
type MockIssueFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockIssueFetcherMockRecorder
}

// MockIssueFetcherMockRecorder is the mock recorder for MockIssueFetcher.
type MockIssueFetcherMockRecorder struct {
	mock *MockIssueFetcher
}

// NewMockIssueFetcher creates a new mock instance.
func NewMockIssueFetcher(ctrl *gomock.Controller) *MockIssueFetcher {
	mock := &MockIssueFetcher{ctrl: ctrl}
	mock.recorder = &MockIssueFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssueFetcher) EXPECT() *MockIssueFetcherMockRecorder {
	return m.recorder
}

// MyIssues mocks base method.
func (m *MockIssueFetcher) MyIssues() ([]usecase.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MyIssues")
	ret0, _ := ret[0].([]usecase.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MyIssues indicates an expected call of MyIssues.
func (mr *MockIssueFetcherMockRecorder) MyIssues() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MyIssues", reflect.TypeOf((*MockIssueFetcher)(nil).MyIssues))
}
